---
title: "47956712VoKhuongDuyAssignment1"
output: rmarkdown::github_document
date: "2024-04-24"
---
```{r}
set.seed(10)
```

```{r}
install.packages("moments",repos = "http://cran.us.r-project.org")
library(boot)
library(moments)
```

## Question 1

```{r}
Assignment1_Dataset_2024 <- read.csv("Assignment1_Dataset_2024.csv")
attach(Assignment1_Dataset_2024)
summary(Assignment1_Dataset_2024)
```
```{r}
Assignment1_Dataset_2024$state <- as.factor(Assignment1_Dataset_2024$state)
Assignment1_Dataset_2024$gender <- as.factor(Assignment1_Dataset_2024$gender)
summary(Assignment1_Dataset_2024)
```

```{r}
hist(weight, xlab="Weight", main="Histogram of Weight")
```
```{r}
skewness(weight)
```

```{r}
hist(distance, xlab="Distance", main="Histogram of Distance")
```
```{r}
skewness(distance)
```

```{r}
hist(age, xlab="age", main="Histogram of Age")
```
```{r}
skewness(age)
```
```{r}
hist(carage, xlab="Car Age", main="Histogram of Car Age")
```
```{r}
skewness(carage)
```

```{r}
barplot(table(state),xlab="State", ylab="Frequency", main="Frequency of States")
```


```{r}
barplot(table(gender), xlab="Gender", ylab="Frequency", main="Frequency of Gender")
```

## Question 2
```{r}
model1_full <- glm(Counts~weight+distance+age+carage+gender+state, data=Assignment1_Dataset_2024, family=poisson(link=log), offset=log(exposure))
summary(model1_full)
```
```{r}
model1_red <- glm(Counts~weight+distance+age+carage+gender, data=Assignment1_Dataset_2024, family=poisson(link=log), offset=log(exposure))
summary(model1_red)
```
```{r}
LR <- model1_red$deviance - model1_full$deviance
LR
```
```{r}
qchisq(p = .05, df = 4, lower.tail = FALSE) 
```
```{r}
model1 <- model1_red
coefficients(model1)
```

```{r}
new_data = data.frame(weight=2000, distance=15, age=30, carage=4, gender="female", state="NSW", exposure=1)
predict(model1,new_data,type="response")
```

```{r}
xage_1 <- seq(min(age),max(age),0.5)

yage_1 <- predict(model1, list(age=xage_1,
                weight=rep(2000,length(xage_1)),
                distance=rep(15, length(xage_1)),
                age=rep(30,length(xage_1)),
                carage=rep(4,length(xage_1)),
                gender=rep("female",length(xage_1)),
                state=rep("NSW",length(xage_1)),
                exposure=rep(1, length(xage_1))), 
type="response")
plot(xage_1,yage_1,xlab="age",ylab="intensity")
```

## Question 3: 
```{r}
model2_full <- glm(Counts~weight+distance+age+carage+gender+state+I(weight^2)+I(distance^2)+I(age^2)+I(carage^2), data=Assignment1_Dataset_2024, family=poisson(link=log), offset=log(exposure))
summary(model2_full)
```
```{r}
step(model2_full, direction="backward")
```

```{r}
model2 <- glm(formula=Counts~weight+distance+age+carage+gender+I(distance^2)+I(age^2)+I(carage^2),data=Assignment1_Dataset_2024, family=poisson(link=log), offset=log(exposure))
summary(model2)
```
```{r}
coefficients(model2)
```

```{r}
predict(model2,new_data,type="response")
```

```{r}
xage_2 <- seq(min(age),max(age),0.5)
yage_2 <- predict(model2, list(age=xage_2,
                weight=rep(2000,length(xage_2)),
                distance=rep(15, length(xage_2)),
                age=rep(30,length(xage_2)),
                carage=rep(4,length(xage_2)),
                gender=rep("female",length(xage_2)),
                state=rep("NSW",length(xage_2)),
                exposure=rep(1, length(xage_2))), 
type="response")
plot(xage_2,yage_2,xlab="age",ylab="intensity", col="red", ylim=c(0.04,0.12))
points(xage_1,yage_1,col="blue")
```

## Question 4
```{r}
LR_2 <- model1$deviance - model2$deviance
LR_2
```

```{r}
qchisq(p = .05, df = 3, lower.tail = FALSE)
```
## Question 5 
```{r}
cv.error_model1=cv.glm(Assignment1_Dataset_2024,model1,K=10)$delta[1]
cv.error_model2=cv.glm(Assignment1_Dataset_2024,model2,K=10)$delta[1]
cv.error_model1
cv.error_model2
```

output: github_document

